### ISSUE TITLE
Scrolling message via Ctrl-Left/Right

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nostalgy/nostalgy#6] opened 2015-03-23 18:27 UTC
```
What steps will reproduce the problem?
1. Open Thunderbird
2. Press Control button plus Left/Right Arrow to scroll up/down
3. Message does not scroll

What is the expected output? What do you see instead?
The expected output is to scroll the message up/down via the keyboard with 
Ctrl+Left Arrow/Right Arrow, respectively, but it isn't working

What version of the product are you using? On what operating system?
nostalgy 0.2.27, TB 9, Windows 7, 

Please provide any additional information below.
sorely missed functionality :)

```

Original issue reported on code.google.com by `wesley.k...@gmail.com` on 16 Jan 2012 at 5:54

**Comment by jjeziorny** [comment] 2016-01-18 17:02
Humm, using 0.2.33 with TB 38.5.1  Linux + Awesiome and cannot scroll messages with Ctrl-Left/Right

Is broken again or is it something on my config?

**Comment by caugner** [comment] 2020-02-20 18:50
Reproducible with Nostalgy 0.3 and TB 68.4.2: Scrolling a message horizontally with <kbd>Ctrl</kbd> + <kbd>Up/Down</kbd> works with Nostalgy disabled, but doesn't work with Nostalgy enabled.

**Comment by caugner** [comment] 2020-02-21 09:42
The reason for this is that the <kbd>Ctrl</kbd> + <kbd>Left/Right</kbd> is defined in Nostalgy to `Scroll the message [vertically] from the thread pane`.

**Solutions**:

1. Restrict Nostalgy's own <kbd>Ctrl</kbd> + <kbd>Left/Right</kbd> shortcut to the thread pane.
2. Add a shortcut <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Left/Right</kbd> to `Scroll the message horizontally from the thread pane`.

**Comment by caugner** [comment] 2020-02-21 09:45
I have to correct myself: This issue is talking about regular [vertical] scrolling using Nostalgy's own <kbd>Ctrl</kbd> + <kbd>Left/Right</kbd> shortcut, and this is working as expected in 0.3 with TB 68.

Therefore I'm closing this issue (even though the horizontal scroll shortcut would be a nice enhancement).

**Closed by caugner** 2020-02-21 09:45 UTC
Labels: auto-migrated, bug
