### ISSUE TITLE
Compatibility with Thunderbird 60?

### ISSUE THREAD

**Issue by gwhitney** [nostalgy/nostalgy#46] opened 2018-04-25 00:20 UTC
I'm on the Thunderbird beta update channel, and (I believe) when Thunderbird went from 60.0b2 to 60.0b3 it started reported that Nostalgy was incompatible and it auto-disabled it. Just a polite inquiry, are you or others likely to update Nostalgy to be compatible with Thunderbird 60?  Thanks for letting us know.

**Comment by gwhitney** [comment] 2018-04-25 19:31
Update: In Thunderbird 60.0b4 I went to "Edit > Preferences > Advanced" and clicked on "Config Editor" and then changed the value of "extensions.strictCompatibility" to false. This allowed me to re-enable Nostalgy and on Thunderbird restart, it was (pretty much, see below) back to working (yay!). 

The only nit now is that if I use Nostalgy and type in a folder name and move a message there, it used to then work that just hitting the keyboard shortcut again would default to the last used folder. That no longer works; the last used folder is displayed, but hitting "enter" doesn't use it, nor can I select it with arrow keys or anything. My only option is to re-type the folder name. So it would be great if the prior defaulting behavior could be restored, thanks.

**Comment by gwhitney** [comment] 2018-04-26 22:10
Update: In Thunderbird 60.0b4 I went to "Edit > Preferences > Advanced" and clicked on "Config Editor" and then changed the value of "extensions.strictCompatibility" to false. This allowed me to re-enable Nostalgy and on Thunderbird restart, it was (pretty much, see below) back to working (yay!). 

The only nit now is that if I use Nostalgy and type in a folder name and move a message there, it used to then work that just hitting the keyboard shortcut again would default to the last used folder. That no longer works; the last used folder is displayed, but hitting "enter" doesn't use it, nor can I select it with arrow keys or anything. My only option is to re-type the folder name. So it would be great if the prior defaulting behavior could be restored, thanks.

**Comment by alainfrisch** [comment] 2018-04-30 11:53
> Just a polite inquiry, are you or others likely to update Nostalgy to be compatible with Thunderbird 60?

Unfortunately, it's unlikely that I'll be able to work on that soon.

**Comment by fanf** [comment] 2018-05-31 12:02
I'm also testing Nostalgy with tb60, and it seems to work nicely (for now). So perhaps it only need a version bump to tell TB60 that it is compatible with it (and in fact, I don't know how much work it is)

**Comment by gwhitney** [comment] 2018-05-31 17:44
@fanf , under tb60 have you tried saving a message to a folder, then selecting another message, hitting the Nostalgy save key (usually just "s") again, hitting the up arrow once, and then hitting enter? Pre tb60, that would save the second message to the same folder as the first, but now it does nothing; I have to re-type the folder name and press enter. Just wondering if you observe the same difference in behavior with tb60 or not.

**Comment by fanf** [comment] 2018-06-01 07:48
@gwhitney ha, you are right: you can't just hit "arrow up" to select again a directory, even if it is in the list.

**Comment by scottro11** [comment] 2018-07-29 18:33
@gwhitney, thank you. I had just upgraded a FreeBSD install and couldn't get nostalgy working, but making your suggeseted change in about:config fixed it. I only need it to navigate between a large number of directories, and it's still doing that perfectly.

**Comment by ArkanaDaze** [comment] 2018-08-06 17:19
Hello,
I am using TB 61.0.1 and nostalgy (revived through the "extensions.strictCompatibility" set to false tip above) does not seem to work when trying to move messages to different folders.
I will select "s", choose a specific folder using the arrow keys, and when I press Return the selected message stays in the Inbox.
I´m still able to move into different dirs, just not copy/move emails anymore...

**Comment by Anguel** [comment] 2018-08-08 10:44
I am using Nostalgy for Thunderbird automation with Phraseexpress, especially the ESC-ESC combination to quickly go to the message pane from any other field. It's a pity that Thunderbird does not even offer such shortcuts and I don't know of any other extension that does. So far for my case the "extensions.strictCompatibility" workaround seems to work but as many others I would love to see TB 60 compatibility. Are there any plans?

**Comment by JoelAzaria** [comment] 2018-08-08 20:52
Also got it working by changing strictCompatibility as above (thank you!)  
Noticed that the extension works but there is no more 'options' button to set anything (noticed this with other "incompatible" add-ons that started working after setting strict = false)

Anyone have a fix?

Also, add me to the list that would love to see this working in 60.   I was ready to roll back to 58 or to get nostalgy working.  Depending on what does or doesn't work this way I may do that anyway.  

Working Nostalgy > latest Tbird for me!

**Comment by Cito** [comment] 2018-08-09 08:44
@gwhitney in the case you mentioned, when trying to move a second message, not only the arrow-up/down does not work, but if you select the folder in the autocomplete box with the mouse, then the message is moved to some nirvana and cannot be recovered.

**Comment by JoelAzaria** [comment] 2018-08-09 10:46
Rolled myself back to tbird 52.9.1 and all is right in the world again.

For those of you hitting the second save issue, does the "save again to last folder" shortcut (Shift+S) still work for you?
Just a thought.

**Comment by Cito** [comment] 2018-08-09 12:56
@JoelAzaria Shift-S still works. But you have to rely on your memory to know what the last location was.

**Comment by Anguel** [comment] 2018-08-09 13:06
@JoelAzaria Not sure what you mean by "no more options". There is an extra menu Tools > Add-on settings in TB 60.

**Comment by Cito** [comment] 2018-08-09 13:17
@Anguel Nostalgy is listed there, but without an icon. There should be also a "Settings" button in the list of add-ons and a settings option in the context menu when you right-click the add-on. Both are missing.

**Comment by Anguel** [comment] 2018-08-09 13:32
I can go to the settings (German TB60):
![nostalgy_settings_tb60](https://user-images.githubusercontent.com/2046029/43902017-4466d7c2-9be9-11e8-8712-e624882bb33c.png)

**Comment by Cito** [comment] 2018-08-09 13:44
@Angual yes, aside from the missing icon, that works. But the other two ways of configuring the add-on which are more intuitive for users coming from Firefox do not work. Not sure if they never worked or only now in TB60. They work for other add-ons such as "Send later" or "Mail Redirect".

**Comment by hkclark** [comment] 2018-08-09 15:45
I got the upgrade to the official TB 60 early this AM and I'm getting the error below.  It seems really strange because it looks like bindUTF8StringParamater() is still fully supported in the API.  Anyone else running into this or have thoughts on how to avoid it?

```
TypeError: statement.bindUTF8StringParameter is not a function[Learn More]  sqlite.js:25:17
	select chrome://nostalgy/content/sqlite.js:25:17
	find_generic_id chrome://nostalgy/content/nfpredict.js:150:31
	find_folder_id chrome://nostalgy/content/nfpredict.js:159:16
	update_folder chrome://nostalgy/content/nfpredict.js:194:23
	NostalgyMoveToFolder chrome://nostalgy/content/nostalgy.js:608:6
	NostalgyRunCommand chrome://nostalgy/content/nostalgy.js:368:5
	anonymous chrome://global/content/bindings/autocomplete.xml%20line%20422%20%3E%20Function:3:1
	anonymous self-hosted:1020:17
	onTextEntered chrome://global/content/bindings/autocomplete.xml:256:18
	onPopupClick chrome://global/content/bindings/autocomplete.xml:743:11
	onxblmouseup chrome://global/content/bindings/autocomplete.xml:2222:9
```

**Comment by hkclark** [comment] 2018-08-09 18:34
In case others are running into the `statement.bindUTF8StringParameter is not a function` issue, a temporary workaround seems to be: go into the Nostalgy Preferences and uncheck "Use Statistical Prediction".  After that I'm getting the other issues people have mentioned, but at least it mostly works.

**Comment by vcaston** [comment] 2018-08-10 10:45
Can't survive without Nostalgy! Would love to know if/when updated for TB60.

**Comment by fanf** [comment] 2018-08-10 10:55
Would it help if all the people needing nostalgy gave money to financially
help? (or if anyone can contribute code...)

**Comment by vcaston** [comment] 2018-08-10 11:02
Would happily contribute money

**Comment by ArkanaDaze** [comment] 2018-08-10 15:16
+1 Can´t survive without Nostalgy
+2 Would happily contribute money!

I´m seeing some major caveats here: TB60 is a major update, with some important changes under the hood. Although it´s still supposed to support "legacy add-ons" with some simple mods (https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57), after TB62 it looks like this support will become much more challenging (https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_62).

Unfortunately, it doesn´t look like Alain Frisch will be able to provide the (possibly deep) level of TLC in order to make our beloved Nostalgy future-proof...  :-(

Any other ideas? Some kind soul willing to contribute code? Contract programming?  :-)

**Comment by hkclark** [comment] 2018-08-10 16:06
I would be happy to join in on the future maintenance of Nostalgy.  Should we try to organize a group to keep Nostalgy alive since it sounds like Alain is tied up with other things?

I have not done Thunderbird (or Firefox) addon/extension development before, so I would need to come up to speed on the details.  I have been reviewing some of the discussion about how addons are changing in TB 60 and going forward and I'm finding it pretty confusing as to how to navigate the path forward.  I *think* they are saying the future is WebExtensions (like Firefox), but it sounds like you can't do WebExtensions yet... so I'm unclear how to best do this without having to rewrite things multiple times. :-(  It sounds like this is a real mess that's going to be painful for lots of addons (and I can't imagine this is going to be good for the overall Thunderbird community and it's popularity since I'm sure lots of addons are going to be abandoned, causing people to find TB lacking in functionality they are used to, and ultimately leaving Thunderbird). :-(  Hopefully the documentation on TB addons development are cleanup up soon so it's less confusing.

**Comment by ArkanaDaze** [comment] 2018-08-10 16:29
@hkclark I fully agree with you! Hopefully, the TB developers do seem to be aware of the pitfalls moving forward and they seem to be in touch with the TB add-ons development community and trying to come up with compatibility/migration solutions for existing add-ons moving forward.

There´s a lot of discussion regarding this here: https://groups.google.com/forum/#!topic/tb-planning/mDj7fFKKPOk
Since everything seems to be in flux at the moment, one possible idea might be to get in touch with one of the people in the Google Forum above to help with some "emergency fixing" of Nostalgy? Axel Grude, for example, might be a possible contact since he seems to be helping other people address compatibility issues with their add-ons...

**Comment by lepokle** [comment] 2018-08-14 21:26
Hi @aaschmid, do you have enabled "statistical prediction"? This seems to be the only setting that does not work with TB60:
```
statement.bindUTF8StringParameter is not a function
```

**Comment by lepokle** [comment] 2018-08-14 22:18
I've just created PR #51 which fixes the problem for now. I've also created a release in my forked repo for the impatient: https://github.com/lepokle/nostalgy/releases/tag/v0.2.36

**Comment by aaschmid** [comment] 2018-08-14 22:27
@lepokle: I don't use "statistical prediction" but if I activate it, Nostalgy does not work ...

Can you also reproduce the problem with the not working arrow-up after pressing `S` or `G`?

**Comment by hkclark** [comment] 2018-08-14 22:44
@lepokle Excellent work!  Thank you so much.  I started digging into it but between being new to extension development and having limited time, I put it on hold.  So this is great of you -- thanks!

**Comment by JoelAzaria** [comment] 2018-08-15 00:02
@lepokle Thank you for this.  Does this fix any of the issues or just the compatibility (version bump)?

I still need strictCompatibility off for other extensions so if it's just a version bump, for me there's no hurry.

**Comment by hkclark** [comment] 2018-08-15 02:15
@JoelAzaria For me this fixes "statistical prediction" and it bumps the version to say it supports a a "maxVersion" of TB = 60.  I believe it still requires strictCompatiblity off, but like you have it it off for other extensions, so I haven't tried it with strictCompatibility on.  Based on my usage over the last few hours it's working great.

**Comment by JoelAzaria** [comment] 2018-08-15 03:00
Thanks @hkclark.  If it says max version = 60 I imagine strictCompat can be off since that's the only thing I believe it does - regulate version checking.  If it fixes the statistical prediction then probably lepokle fixed a couple of things and it might be worth the effort.

**Comment by hkclark** [comment] 2018-08-15 03:59
Oh OK, I assumed strict mode did more than that, but I can see it either way.  I don't think lepokle changed anything other than fixing the SQL access needed for statistical prediction and bumping the number -- his diffs are here: https://github.com/alainfrisch/nostalgy/pull/51/files.  Thanks.

**Comment by lepokle** [comment] 2018-08-15 05:14
@JoelAzaria @hkclark That's correct, I've only fixed the database access and increased the version in install.rdf.
I don't know yet of this is enough to re-enable strictCompatibility nur this should be a quick test.
The plugin now works for my use cases. Of you get aware of any TB60 related bugs, please give exact steps to reproduce. Maybe I can fix them but no guarantees 😊

**Comment by aaschmid** [comment] 2018-08-15 08:38
Pressing `s` (lowercase of course) you are given the five last used folders from history and could navigate directly through them using arrow keys. This does not work any more and yesterday night I couldn't find the cause for it while quickly debugging ... 
I think I have to try with more time :-)

**Comment by JoelAzaria** [comment] 2018-08-16 06:41
@hkclark 
> Oh OK, I assumed strict mode did more than that, but I can see it either way
I am making an assumption - I do not know for sure.  Just to be clear.

I have not yet installed @lepokle's version but afaict pressing 's' and typing a folder name results in nothing moving anywhere for me (using alanfrisch's last release to be clear.)

TB60 is shaping up to be more trouble then it's worth 😞

**Comment by ArkanaDaze** [comment] 2018-08-16 16:17
I have installed @lepokle's version just now in TB60.0 (64-bit)
- My work environment is a MacBook Pro running macOS High Sierra 10.13.6 (17G65)
- Before installing this version I reset "extensions.strictCompatibility" in TB back to "true" (default)
- I´ve kept "statistical prediction" enabled in Nostalgy, as for older versions of TB I had been using

The extension seems to be working fine now for my keyboard based use cases. I´ve tested the following:
- Commands "g", "G", "b", "B", "s", "S", "c", "C" all work as intended
- I am using the arrow keys to select target folders, not the mouse

Opening Nostalgy Preferences through the Tools -> Add-on Preferences -> Nostalgy menu does not work reliably. Sometimes I am able to get the screen to open, but other times it does nothing...

All in all, it seems to be working acceptably now, so BIG THANK YOU to @lepokle and everybody else that has been involved and contributed to move this forward!

**Comment by postiffm** [comment] 2018-08-16 20:27
Great to hear about the fork that has fixed the upgrade issues. For me, Thunderbird is almost unusable without Nostalgy. It saves so much time it is amazing.

**Comment by JoelAzaria** [comment] 2018-08-17 01:06
@ArkanaDaze 
> The extension seems to be working fine now for my keyboard based use cases.
The issue appears the SECOND TIME you use the 's' shortcut.  Arrow keys (up/dn) will not work until you start typing some text.

Can you confirm this is fixed in @lepokle's version?
thx.

**Comment by ArkanaDaze** [comment] 2018-08-17 11:13
@JoelAzaria 
When I use the "s" shortcut I will not get a folder selection window until I start typing some text. After I get the window arrow keys will work as expected.

BTW, I just noticed that accessing extension Preferences through the Tools -> Add-on Preferences -> [extension name] is working unreliably for all extensions I have installed, not just for Nostalgy. It seems this is a TB60 related bug and not directly related to Nostalgy...

**Comment by vanous** [comment] 2018-08-24 06:09
Omg, thank you for mentioning strictCompat, i had tried to combine other extensions to work around (Quick Folder Move + Dorando Koeyconfig) but the Quick Folder Move is actually... very slow :) Back in business with Nostalgy.

**Comment by amaramrahul** [comment] 2018-08-25 03:41
Using lepokle release with Thunderbird 60 on El Capitan. Seems to works fine. Thanks a ton!

**Comment by neufeind** [comment] 2018-09-04 12:36
I can confirm that strictCompatibility to false (almost) makes it work for me - with the exceptions mentioned here, but the basics are working fine.

**Comment by ULinn** [comment] 2018-09-05 11:36
@lepokle Thank you for your fix, you made my day! Using "s" and "S" now works again with Thunderbird 60.0, extensions.strictCompatibility is set back to TRUE. Perfect!
I'd also be happy to pay for an updated version that is (and will remain) compatible to the latest thunderbrid.

**Comment by alainfrisch** [comment] 2018-09-05 11:52
Many thanks to @lepokle and sorry for the delay.  I've merged his PR and submitted a new version to https://addons.thunderbird.net .

**Comment by JoelAzaria** [comment] 2018-09-05 23:48
Good to see @alainfrisch still active here.  Please recognize that @lepokle version only fixes the main impediment.  
There are other niggling issues that persist and need attention please.

Thank you @alainfrisch

**Comment by klausatlas** [comment] 2018-09-10 08:07
Sorry, maybe I am just too stupid but the last version I can see is 0.2.35 from last December.

**Comment by alainfrisch** [comment] 2018-09-10 08:15
The next version is in the review queue.

**Comment by neufeind** [comment] 2018-09-12 09:53
Is it available for download somewhere? It's not the nostalgy-current.xpi link from the main page of this github-project, is it?

**Comment by tuxayo** [comment] 2018-09-13 07:42
@neufeind It is
- download
- extract the .xpi (it's a zip format)
- open install.rdf
- em:version="0.2.36"
- https://github.com/alainfrisch/nostalgy/commit/e6b1084f966ecb4e9e6ec62a7192ced760e9c87c#diff-e4eb329834da3d36278b1b7d943b3bc9R1
- Fix for TB 60: 0.2.36

**Comment by tuxayo** [comment] 2018-09-23 22:09
And it's finally on AMO! :D
https://addons.thunderbird.net/en-US/thunderbird/addon/nostalgy/

**Comment by jlanza** [comment] 2018-10-10 08:19
Is fully functional in TB60 up with the new release? I'm still in 52.9.1 waiting for most of my add-ons to be supported.

**Comment by tuxayo** [comment] 2018-10-10 10:03
What is missing? Even statistical prediction seems to work (I'm a new user so I might not notice if it doesn't work as good)

**Comment by gwhitney** [comment] 2018-10-11 02:55
@tuxayo, earlier in this thread you can see the outstanding problems: see https://github.com/alainfrisch/nostalgy/issues/46#issuecomment-411683919 and https://github.com/alainfrisch/nostalgy/issues/46#issuecomment-384407096 (is there a quicker/more convenient way to refer to earlier posts in this thread than pasting the links?)

**Comment by dsteinkopf** [comment] 2018-10-12 04:12
also see #53 and #56

**Comment by greentux** [comment] 2018-10-25 16:28
Just upgraded to TB 60.2.1 an recent nostalgy. But tab-key does not work anymore.  I can use the arrow-key workaroud, but thats ugly..

**Comment by JoelAzaria** [comment] 2018-10-26 16:30
Adding this here since I believe it's a TB 60 thing and we've fleshed out other "residual" issues here..

After I've saved a message to a folder, the status bar shows where 'Shift+S" would go (which *should* be the last saved folder/dest).  It doesn't show the last destination, it shows some previously used dest that I haven't touched in an age.   Like it's not updating where it last saved a message to.

It's possible this is connected to people's complaint above (@cito and @gwhitney for example) that when the arrow keys are 'stuck' on second move, *clicking* on that list sends to the bitbucket.   It might be that it's  just sending to this unrelated dest like Shift+S would and not what's shown in the list (which may be why the arrow isn't working?)
Dunno, I'm fishing here, but hoping any add'l info points someone to the right place in the code.

If anyone else has the status bar on in TB (or willing to turn it on to check), can you verify the behavior please and confirm?
thx.

**Comment by caugner** [comment] 2020-02-21 10:41
The latest Nostalgy version 0.3 is now compatible with the latest TB version 68.

**Closed by caugner** 2020-02-21 10:41 UTC
