### ISSUE TITLE
Keyboard shortcuts stop working until Thunderbird is restarted

### ISSUE THREAD

**Issue by PatonLewis** [nostalgy/nostalgy#48] opened 2018-06-15 18:54 UTC
With a recent Thunderbird update (I'm using Thunderbird 52.8.0 (64-bit) on macOS 10.12.6) the nostalgy keyboard shortcuts stop working after a while, and will not function again until Thunderbird is restarted. This is actually a long-standing bug, but it used to happen infrequently. Now it happens daily.

**Comment by PatonLewis** [comment] 2018-12-23 00:42
This is still an issue on Thunderbird 60.3.3 (64-bit) and macOS 10.14.2.

**Comment by caugner** [comment] 2020-02-21 10:58
@PatonLewis Do you still experience this issue with Nostalgy 0.3 on Thunderbird 68?

**Comment by PatonLewis** [comment] 2020-03-03 19:32
I've been using opto's fork with TB68, and haven't seen the problem yet with that forked version.

**Comment by caugner** [comment] 2020-03-04 08:34
@PatonLewis Could you please try if the issue is also resolved in the version from Thunderbird Add-ons (which should contains opto's fix): https://addons.thunderbird.net/thunderbird/addon/nostalgy/

**Comment by PatonLewis** [comment] 2020-03-16 19:19
@caugner 26 hours so far, and no problems yet.

**Comment by caugner** [comment] 2020-03-17 10:28
Thank you, that sounds good.

I will close the issue for now, but don't hesitate to comment if the problem persists, and we'll reopen it.

**Closed by caugner** 2020-03-17 10:28 UTC
Labels: bug
