### ISSUE TITLE
Message saved in wrong folder, of wrong email account

### ISSUE THREAD

**Issue by perlyking** [nostalgy/nostalgy#15] opened 2015-06-16 15:01 UTC
Version: 0.2.3.3 on Win7-64, T'bird 38.0.1

I have two email accounts, A and B

B (a gmail one as it happens) has a folder called Foo.

When I select a message in my top-level Inbox for B, and press 's' to save it, and choose folder B->Foo, Nostalgy saves it in a folder Bar in account A.

This only happens with one or two folders for account B. 

For clarity let me say that the folder names Foo and Bar are not lexically similar.

Is there some index file that might have become corrupted that I can remove/rebuild?

**Comment by alainfrisch** [comment] 2015-06-16 15:48
There is a known issue with mouse selection (clicks).  Can you confirm that if you choose the target folder with up/down keys, this works fine?

**Comment by perlyking** [comment] 2015-06-16 19:32
Yes, you're quite right: it's only when you use the mouse.

**Comment by themonman** [comment] 2016-01-10 02:17
Hello, I also experienced this problem. Is there a fix forthcoming soon?

**Comment by caugner** [comment] 2020-02-20 19:30
I cannot reproduce this with 0.3 and TB 68, but it might have never been reliably reproducible.

It would be good to have some theory as to when this happens, e.g.

* if the window was previously resized
* if the status bar is hidden
* if two accounts have similarly named folders
* etc.

Closing this for now, until someone catches the issue in the wild and can provide some clues.

**Closed by caugner** 2020-02-20 19:30 UTC
Labels: bug
