### ISSUE TITLE
Nostalgy shortcuts activating within Google Calendar Tab add-on

### ISSUE THREAD

**Issue by chattgithub** [nostalgy/nostalgy#41] opened 2018-01-03 00:51 UTC
When I open a Google Calendar Tab tab in Thunderbird 52.5.2, and attempted to edit the event, Nostalgy codes are triggering when I try to capitalize letters in, for example, the "details" field of the calendar event.  And, I am not able to enter text into the field, if the text I type corresponds to any of my Nostalgy shortcuts. This has been the case since the new Google Calendar format activated on my google account.  Is there a way to make these two add-ons compatible?

**Comment by hleskien** [comment] 2018-05-11 10:43
This also happens with the Sieve plugin. A solution might be that Nostalgy only accepts shortcuts on those views / tabs that it is meant to work on.

**Comment by amaramrahul** [comment] 2019-03-21 06:31
I am also facing the same issue. I have "Open Google Calendar" addon and whenever I try to type a letter in the event description, which is also a keyboard shortcut for Nostalgy, Nostalgy pops-up. Reall annoying and I am not aware of any known workaround. Is there any way that nostalgy can be restricted to only Email view / tab.

**Comment by amaramrahul** [comment] 2019-03-21 06:36
This is a duplicate of https://github.com/alainfrisch/nostalgy/issues/22

**Comment by caugner** [comment] 2020-02-21 10:39
Closing, as this is indeed a duplicate.

**Closed by caugner** 2020-02-21 10:39 UTC
Labels: duplicate
