### ISSUE TITLE
"Use Statistical Prediction" Option Fails with TB60

### ISSUE THREAD

**Issue by hkclark** [nostalgy/nostalgy#50] opened 2018-08-09 19:52 UTC
If you have TB60 and try to enable the "Use Statistical Prediction" you get the following error every time you move and email using Nostalgy.  (Note: I'm on the full TB60 release vs. a beta).

```TypeError: statement.bindUTF8StringParameter is not a function[Learn More]  sqlite.js:25:17
	select chrome://nostalgy/content/sqlite.js:25:17
	find_generic_id chrome://nostalgy/content/nfpredict.js:150:31
	find_folder_id chrome://nostalgy/content/nfpredict.js:159:16
	update_folder chrome://nostalgy/content/nfpredict.js:194:23
	NostalgyMoveToFolder chrome://nostalgy/content/nostalgy.js:608:6
	NostalgyRunCommand chrome://nostalgy/content/nostalgy.js:368:5
	anonymous chrome://global/content/bindings/autocomplete.xml%20line%20422%20%3E%20Function:3:1
	anonymous self-hosted:1020:17
	onTextEntered chrome://global/content/bindings/autocomplete.xml:256:18
	onPopupClick chrome://global/content/bindings/autocomplete.xml:743:11
	onxblmouseup chrome://global/content/bindings/autocomplete.xml:2222:9
```

**Comment by lepokle** [comment] 2018-08-14 22:16
Could be fixed with PR #51

**Comment by lepokle** [comment] 2018-08-14 22:18
For the impatient: https://github.com/lepokle/nostalgy/releases/tag/v0.2.36

**Comment by hkclark** [comment] 2018-08-14 22:44
@lepokle Great job!  Seems to be working well for me.  Thanks!

**Comment by tuxayo** [comment] 2018-08-22 15:27
Related to #46

**Comment by Wiiilmaa** [comment] 2018-09-10 11:31
@lepokle Works for me as well! Thank you!

**Comment by wlkath** [comment] 2019-05-11 15:05
With Thunderbird 60.6.1 and Nostalgy version 0.2.36 (and with "extensions.strictCompatibility" set to false), if "Use Statistical Prediction" is on, I select a message, and hit "s" to save it, the "Move Messages to:" box appears but is empty and the Error Console generates:

TypeError: folder is null folders.js:89:1
	NostalgyShortFolderName chrome://nostalgy/content/folders.js:89:1
	NostalgyFolderName chrome://nostalgy/content/folders.js:107:12
	f chrome://nostalgy/content/folders.js:143:44
	NostalgyGetAutoCompleteValues chrome://nostalgy/content/folders.js:155:8
	startSearch jar:file:///Users/kath/Library/Thunderbird/Profiles/XXXXXXXX.default/extensions/nostalgy@alain.frisch.xpi!/components/nostalgy-autocomplete.js:64:25
	NostalgyShowRecentFoldersList chrome://nostalgy/content/nostalgy.js:348:3
	NostalgyCmd/< chrome://nostalgy/content/nostalgy.js:324:4

Our institution switched from an Exchange server to outlook365.com around the same time of the most recent Thunderbird update, so I'm unsure which of the two changes might be involved. 

Is anyone else seeing this error?   Thanks!

**Comment by IGZmanuelMartinVivaldi** [comment] 2019-05-13 08:47
@wlkath I just activated "Use Statistical Prediction" and restarted TB and is working fine with v 60.6.1 and Nostalgy v 0.2.36. I don't know if errors could happen after some usage, but for now iw working fine

**Comment by wlkath** [comment] 2019-05-14 01:38
@IGZmanuelMartinVivaldi Thanks very much for letting me know that it should work.   Your comment encouraged me to dig a little deeper, and in the end I decided to delete the prior statistical prediction database, nfpredict.sqlite, and start all over again.  Specifically, I removed Nostalgy, deleted all the nostalgy items from pref.js, and deleted nfpredict.sqlite.   After reinstalling Nostalgy, restarting, and a bit of retraining, Statistical Prediction is working for me again.   

I will just add that being without Nostalgy's full capabilities for a while it has been driven home to me again just how incredibly useful it is and how much I rely on it. 

Thanks, all!

**Comment by IGZmanuelMartinVivaldi** [comment] 2019-05-14 09:28
@wlkath nice to know it worked, thanks. 
PD: and yes, Nostalgy is really useful and awesome

**Comment by caugner** [comment] 2020-02-21 11:17
The two stack traces posted [here](https://github.com/nostalgy/nostalgy/issues/50#issue-349266603) and [here](https://github.com/nostalgy/nostalgy/issues/50#issuecomment-491518598) are not equivalent.

The first one (= this issue) is unfortunately missing the error message, but the conversion sounds like the `nfpredict.sqlite` SQLite database got corrupted.

The second one looks like a recent folder either didn't exist or its name (interpreted as regex) didn't match itself (e.g. due to a character having a meaning in regex).

Closing this for now, because it doesn't seem to be easily reproducible and is likely even fixed.

**If you experience any of these two issues**, please comment below and

* provide both the full error message and the stacktrace,
* mention whether you have folder names with special characters or non-latin characters (e.g. Chinese, Cyrillic, Persian etc.),
* mention whether you did any specific actions before the error occurred (like renaming or deleting folders),
* mention whether your TB has some abnormal behaviour (like an inaccessible IMAP folder, for instance).

**Closed by caugner** 2020-02-21 11:17 UTC
