### ISSUE TITLE
remove annoyting static status bar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nostalgy/nostalgy#8] opened 2015-03-23 18:27 UTC
```
What steps will reproduce the problem?
1. install nostalgy

What is the expected output? What do you see instead?
A clean status bar.

What version of the product are you using? On what operating system?
0.2.3.1 on TB24 on Ubuntu 12.04

Please provide any additional information below.

See also https://groups.google.com/forum/#!searchin/nostalgy-extension/status
```

Original issue reported on code.google.com by `adr...@gmail.com` on 4 Oct 2013 at 2:12

**Comment by caugner** [comment] 2020-02-20 19:03
I'm not exactly sure what the reporter means:

1. They would like to hide the `save (S) copy (C) go (G)` element from the status bar (e.g. with a preference).
2. They would like to hide the status bar, which can already be done in TB via the menu: `View / Toolbars / Status Bar`*

Since this is not clear, I'm closing this issue for now. Feel free to open a new issue with a more detailed description of the expected behavior.

**Closed by caugner** 2020-02-20 19:03 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
