### ISSUE TITLE
Nostalgy on TB 60.3.1 acting strangely

### ISSUE THREAD

**Issue by cjholly** [nostalgy/nostalgy#60] opened 2018-11-21 18:19 UTC

**Comment by cjholly** [comment] 2018-11-21 18:23
Nostalgy seems to be still functioning on Thunderbird 60.3.1, but some display issues. The memory in the picklist is gone when pressing 'S' for example. It seems to remember only the last selection whereas it use to remember back several selections.  Also just discovered rules (duh!) and the file name drop down menu is blank when creating a new rule, but at least I can arrow up and down to eventually get what I am looking for. Hope you can keep this going. Wish I could program so I could help. --Chris

**Comment by ziomau10** [comment] 2018-12-08 09:38
After update to Thunderbird 60.3.3 (32-bit), and latest Nostalgy (don't know where to look for release number), I also experience the same problems.
It seems to remember the last search, and even if the edit are is blank only the searched folders are shown.
Additionally it seems that in this case the arrow keys to scroll the list does not work.
As an example I searched "FA_V", then pressed ESC. After I pressed s to save, and in the list only apperas the folders previously searched:
![image](https://user-images.githubusercontent.com/1978719/49684530-45c02b00-fad5-11e8-843f-52bb3d1168bd.png)
I'll try to be more precise about which condition triggers this behavior after some further test

**Comment by h271fa** [comment] 2018-12-14 20:00
I have same issue. 
Workaround is to 
- press left arrow, then up arrow to get last used folder list.
- downgrade to TB 52.9.1 https://ftp.mozilla.org/pub/thunderbird/releases/52.9.1/

I have chosen the second option. Hope to get this issue investigated and fixed.

**Comment by cjholly** [comment] 2018-12-14 23:01
This was a great tip. It did not work for me but Alt-Down_Arrow brought up the last used folder list. Also, I could swear that software is predicting where to send emails, even when I have not created a rule. I don't remember it doing that before. At least the version I was using, which I think was up to date. Perhaps I was just clueless and now I am woke! --Chris

**Comment by ziomau10** [comment] 2018-12-15 09:19
I don't think this issue should be closed ...
The workaround seems to work, but still I believe this is not the intended behavior.
So to close this issue I think there should be a fix, or an official declaration that this is the intended behavior.
Useless to say that I don't like how Nostalgy works now and I prefer the original behavior.

**Comment by martin8032** [comment] 2018-12-15 09:38
I agree that we should not close this ticket but address the issue. The new behaviour is less useful than the old one.

**Comment by h271fa** [comment] 2018-12-16 11:04
I agree, the first workaround was not working form me - it slowed down managing email quite a lot. That is why I did downgrade.

**Comment by rogerval** [comment] 2018-12-24 20:35
Pleased to say that the latest development version (as of 25/12/18) seems to have brought back the full list when pressing s (even with TB 60.4.0) so that's great. :-)
However, I've noticed that as of TB 60.x.x the highlight no longer follows the mouse pointer... was that ever intended as a feature, or just a happy accident (so to speak) ? 
Thanks to the devs for their hard work. :-)

**Comment by kwrobel** [comment] 2019-01-07 17:24
I'd like to chime in on the subject as it was brought to my attention by and end-user using this plugin here at work. She noticed the same behavior that was described above (S and then arrow keys not working), but only on the second go around. In addition to that, though, she found that when she click on the first selection that shows up in the drop down, the selected email will not be moved into the selected folder, but instead into an entirely different folder. In her case, it was "Archive->Local->Inbox". She uses Thinderbird for Windows, and so I tested this on my Mac as well. In my case, the email got moved to "Local->Trash" !!! Should this be a separate issue? Or is this related to the issue described here?

**Comment by cjholly** [comment] 2019-01-07 18:07
The last behavior below is happening to me too. A folder pick list shows 
up with just the one folder, and so before the TB upgrade, this mean 
pressing enter would send it to that folder, but not now. I either need 
to enter the letters for that folder or do the left right up down arrow 
dance (I have not figured out the best way to do this yet, or if it even 
matters). I will try to pay more attention to when the folder drop down 
list shows the one folder I want but sends the email somewhere else if I 
don't enter the letters. --Chris

**Comment by h271fa** [comment] 2019-01-08 19:10
@kwrobel @cjholly did you try latest version provided by @alainfrisch 

> You can also try the latest development version from http://alain.frisch.fr/info/nostalgy-current.xpi

**Comment by lilive** [comment] 2019-02-02 08:16
Hi,
the latest development version from http://alain.frisch.fr/info/nostalgy-current.xpi solved the problem for me, the recent folders popup menu is back and the arrow keys work.
I just discovered the problem today. This is a good occasion to thanks the developers for this addon !

**Comment by garyfritzz** [comment] 2019-05-30 16:39
The latest XPI from Alain's site also resolved the problem for me.  I was running the official newest release, but either they're taking many months to update things, or Alan hasn't submitted this latest.

But you can get it at the link above, and it seems to work!

**Comment by caugner** [comment] 2020-02-22 00:46
Closing this issue in favor of #75, which seems to describe the same problem, but with a clearer issue title.

**Closed by caugner** 2020-02-22 00:46 UTC
