### ISSUE TITLE
Nostalgy 1.0.21 doesn't work with Thunderbird 78

### ISSUE THREAD

**Issue by Chris-Hibbert** [nostalgy/nostalgy#93] opened 2020-07-26 22:59 UTC
I recently upgraded Thunderbird to release 78 on my MacBook. The add-ons page shows that 1.0.21 is   installed and turned on, however, I haven't figured out how to invoke Nostalgy. 

Does anyone know what it takes to move messages to other folders using the keyboard? It's very irritating to have to go back to mouse-and-menu or using `^ F2` and then navigating to `Message>Move>Recent`.

**Comment by rmmbr** [comment] 2020-07-27 05:07
Duplicate of #85

**Comment by MLopez-Ibanez** [comment] 2020-07-29 08:25
> I recently upgraded Thunderbird to release 78 on my MacBook. The add-ons page shows that 1.0.21 is installed and turned on, however, I haven't figured out how to invoke Nostalgy.
> 
> Does anyone know what it takes to move messages to other folders using the keyboard? It's very irritating to have to go back to mouse-and-menu or using `^ F2` and then navigating to `Message>Move>Recent`.

Chris, as bug #85 shows, the add-on doesn't work at all on TB 78. As far as I know, there is no other add-on that provides this functionality. if you need it, the best option is to downgrade to TB 68 (if you kept a backup of your profile). You can close this bug as a duplicate of #85 and be notified of any updates.

**Comment by mjgreis** [comment] 2020-11-02 18:05
It's extraordinarily frustrating that Thunderbird upgrades users without their knowledge or permission.  A lot of TB users depend on add-ons to make the platform usable and effective, and major upgrades that blow away large numbers of add-ons is arrogant and unhelpful.  

I had been tracking TB 78 and saw that Nostalgy would no longer work.  My other critical add-ons had versions or plans for TB 78.  Nostalgy's ability to quickly file e-mails into folders with keystrokes and its ability to remember/predict is so powerful.  I had tried to avoid the upgrade, but somehow got nailed anyway.  I'd rather not downgrade to TB 68 - that's a fair amount of work and may cause other problems.  

My question is for the author of Nostalgy.  This isn't your fault, or even your responsibility.  But do you plan to provide a version of Nostalgy that will work with TB 78?  How can Nostalgy users help you? 

Thanks!

**Comment by alainfrisch** [comment] 2020-11-03 08:59
Hi @mjgreis. See #85.  In a nutshell: Nostalgy would require an almost full rewrite to work with TB78, which I won't be able to do.  I'm not even sure I'd be able to review in sufficient detail such a rewrite from an external contributor, and I don't feel like merging something without proper review (considering that any problem can open the door to your inbox...).  At this stage, the most realistic option, I think, is to switch to the Quick Folder Move extension which provides some features from Nostalgy (basic ability to move messages and jump to a folder, using the keyboard) -- and perhaps to convince the author of this extension to extend features with more from Nostalgy.  If someone wants to somehow fork QFM to extend it with Nostalgy features and create a new extension, that could also be great, but I'm afraid this will become a new extension (no auto-upgrade from Nostalgy, for the security reason mentioned above).

**Closed by alainfrisch** 2020-11-03 08:59 UTC
